import Pwa from './Pwa';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        {children}
        <Pwa />
      </body>
    </html>
  );
}
