import Pwa from './Pwa';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  appleWebApp: {
    title: 'Skin Sensei',
    statusBarStyle: 'black-translucent',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body>
        {children}
        <Pwa />
      </body>
    </html>
  );
}
