import './globals.css';
import { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    apple: '/favicon.png',
    other: {
      rel: 'apple-touch-startup-image',
      url: '/favicon.ico',
    },
  },
  appleWebApp: {
    title: 'Skin Sensei',
    statusBarStyle: 'black-translucent',
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='es'>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
