import Pwa from './Pwa';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    apple: '/favicon.png',
    other: {
      rel: 'apple-touch-startup-image',
      url: '/favicon.ico',
    },
  },
  appleWebApp: {
    title: 'Skin Sensei',
    statusBarStyle: 'black-translucent',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body>
        {children}
        <Pwa />
      </body>
    </html>
  );
}
